Magic: StorageAccessbile Based Simulations (#1831)
Follow up to
https://github.com/cowprotocol/services/pull/1827#discussion_r1310425237
- thanks @fleupold for the wonderful idea!

This PR changes instances of `eth_call` with state override simulations
**where we are only overriding the Settlement contract code** to make
use of `StorageAccessible`. It does this with an additional support
`Reader` contract in order to avoid needing to manage deployments
on-chain for the `StorageAccessible` target (i.e. the reader logic). See
the comment in the `Reader.sol` file for more details on how this works.

Specifically, we changed the following two simulations to no longer
require state overrides (i.e. we do not need a special node to handle
those requests, and it will Just Work™ on Gnosis Chain):
* Account balance simulations with pre-hooks
* ERC-1271 signature validation with pre-hooks

In a follow up PRs I will:
1. https://github.com/cowprotocol/services/pull/1832
2. Remove the redundant `Web3` strategy for both account balance and
signature verification simulation

### Release notes

Hooks E2E test continues to pass **without the nasty
`----account-balances-optimistic-pre-interaction-handling=true` hack**
which used to disable balance checks for orders with pre-hooks. This
means that not only are we E2E testing that executing orders with
pre-hooks are working, we are also checking that balance simulations
work 🎉.

You can double check this is actually doing something by applying a
patch like this:

```diff
diff --git a/crates/e2e/tests/e2e/hooks.rs b/crates/e2e/tests/e2e/hooks.rs
index 42d8d072..84d978b5 100644
--- a/crates/e2e/tests/e2e/hooks.rs
+++ b/crates/e2e/tests/e2e/hooks.rs
@@ -66,7 +66,7 @@ async fn test(web3: Web3) {
             full: json!({
                 "metadata": {
                     "hooks": {
-                        "pre": [permit, steal_cow],
+                        "pre": [/*permit, */steal_cow],
                         "post": [steal_weth],
                     },
                 },
```

And see the E2E test fail as expected with:

```
thread 'hooks::local_node_test' panicked at 'called `Result::unwrap()` on an `Err` value: (400, "{\"errorType\":\"InsufficientAllowance\",\"description\":\"order owner must give allowance to VaultRelayer\"}")', crates/e2e/tests/e2e/hooks.rs:83:41
```

I also ran the `cargo test -p shared -- --nocapture --ignored
account_balances::simulation` manual test which continues to work.