Make flag command line arguments consistent (#474)
As a follow up to #473, this PR makes all our "flag" command line arguments consistent. That is, you now enable flags with `--my-flag` instead of `--my-flag true`.

Previously, we had used `parse(try_from_str), default_value = "false"` to work around Kubernetes configuration templating limitations. However, those limitations are no longer present (well, they never were... we just figured out how to include conditionals in the template). This PR changes all flags to be more "Unix-y" (and IMO natural), where `--some-flag` is used to enable it instead of `--some-flag true`.

Additionally, I removed the `default_value = "true"` attribute from the `--enable-blockscout` flag. This is for two reasons:
- Since this is a flag that doesn't parse an argument value, this effectively means that it cannot be disabled (since neither `--enable-blockscout false`, `--enable-blockscout=false`, nor `ENABLE_BLOCKSCOUT=false` work).
- Second, this notation doesn't play nicely with `clap`. Specifically, it becomes a "half-flag" where the parser requires a value, but ignores it and bases the flag's value solely on whether or not the flag is present. See example 👇.

<details><summary>Example <code>clap</code> application with a flag and `default_value="true"`</summary>

```rust
use clap::Parser;

#[derive(Debug, Parser)]
struct A {
    /// Flag.
    #[clap(long, env, default_value = "true")]
    flag: bool,
}

fn main() {
    println!("{}", A::parse().flag);
}

```

```
% cargo run -- --flag
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/clap-test --flag`
error: The argument '--flag <flag>' requires a value but none was supplied

For more information try --help

% cargo run -- --flag false
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/clap-test --flag=false`
true

% cargo run -- --flag=false
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/clap-test --flag=false`
true

% FLAG=false cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/clap-test`
true
```

</details>

### Test Plan

CI - no logic changes, just slightly different CLI parameter semantics.

### Release notes

Refactor our deployment configuration to for the following flags:
- [x] `ENABLE_BLOCKSCOUT`
- [x] `SKIP_TRACE_API`
- [x] `ENABLE_EIP1271_ORDERS` (no changes needed - configuration already supported flags)
- [x] `ENABLE_PRESIGN_ORDERS` (no changes needed - configuration already supported flags)